#!/bin/bash

# directories
ast_basdir=/apps/asterisk
ast_etcdir=${ast_basdir}/etc
ast_libdir=${ast_basdir}/var/lib/asterisk

# files
ast_bin=${ast_basdir}/bin/asterisk
ast_pid=${ast_basdir}/var/run/asterisk.pid
ast_cfg=${ast_etcdir}/asterisk/asterisk.conf

# misc
ast_arg="-C ${ast_cfg}"

case "${1}" in
	start)
		if [ ! -d ${ast_libdir} ]; then
	                mkdir -p ${ast_libdir}
		fi

		if [ ! -f  ${ast_libdir}/astdb ] ; then
                    ln -s ${ast_etcdir}/astdb ${ast_libdir}/astdb
                fi

		/sbin/start-stop-daemon --start -p ${ast_pid} -m ${ast_pid} -b -x ${ast_bin} -- ${ast_arg}
		;;
	stop)
		/sbin/start-stop-daemon --stop -p ${ast_pid}
		sleep 1
		rm -f ${ast_pid}
		killall -9 asterisk
		;;
	restart)
		${0} stop
		sleep 1
		${0} start
		;;
	*)
		echo "Usage: ${0} {start|stop}"
		exit 1
		;;
esac

exit 0
